### ISSUE TITLE
Issue running the Molecular Nodes addon on Mac M1

### ISSUE THREAD

**Issue by enzyme69** [BradyAJohnston/MolecularNodes#2]
I installed the addon on Blender 3.1.2 on Mac ARM, and kept getting error when running it:

```
Traceback (most recent call last):
  File "/Applications/BLENDER_31/Blender.app/Contents/Resources/3.1/scripts/modules/addon_utils.py", line 387, in enable
    mod.register()
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.1/scripts/addons/molecular/__init__.py", line 42, in register
    from . import properties, ui, operators, creators
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.1/scripts/addons/molecular/operators.py", line 14, in <module>
    from . import simulate, core
ImportError: cannot import name 'core' from 'molecular' (/Users/jimmygunawan/Library/Application Support/Blender/3.1/scripts/addons/molecular/__init__.py)

```

**Comment by enzyme69** [comment]
Ok apparently I need to install the addon from zip inside the folder:

<img width="585" alt="Screen Shot 2022-04-27 at 12 46 03 pm" src="https://user-images.githubusercontent.com/3952687/165429438-7aeda2dc-cbb0-4a37-950f-6cfa688268bb.png">

Testing this addon now. Thanks!
