### ISSUE TITLE
Can't install Molecular Nodes addon

### ISSUE THREAD

**Issue by MajaDivjak** [BradyAJohnston/MolecularNodes#220]
**Describe the bug**
Have tried installing both Molecular Nodes 2.5.4 and 2.6.2 zip files. The options for installing biotite, install MD Analysis , Install mrc file etc. in the Edit Prefs command window do not work, so I can 't use this addon. The addon appears in the editor window, but is non-functional without the addon preferences.

**To Reproduce**

**Expected behavior**

**Error Codes**
Please include associated error codes that are shown in the python console when the error occurs.
> To view the python console on Windows, `Window` -> `Toggle System Console`, on Mac you must start Blender from the terminal.
```
Read prefs: C:\Users\DivjakMaja\AppData\Roaming\Blender Foundation\Blender\3.5\config\userpref.blend
reloading addon: MolecularNodes 1683878999.2023754 1683879229.4031856 'C:\\Users\\DivjakMaja\\AppData\\Roaming\\Blender Foundation\\Blender\\3.5\\scripts\\addons\\MolecularNodes\\__init__.py'
Modules Installed () from 'C:\\Users\\DivjakMaja\\Downloads\\MolecularNodes_2.6.2.zip' into 'C:\\Users\\DivjakMaja\\AppData\\Roaming\\Blender Foundation\\Blender\\3.5\\scripts\\addons'
reloading addon: MolecularNodes 1683879229.4031856 1683879277.540663 'C:\\Users\\DivjakMaja\\AppData\\Roaming\\Blender Foundation\\Blender\\3.5\\scripts\\addons\\MolecularNodes\\__init__.py'
Modules Installed () from 'C:\\Users\\DivjakMaja\\Downloads\\MolecularNodes_2.6.2.zip' into 'C:\\Users\\DivjakMaja\\AppData\\Roaming\\Blender Foundation\\Blender\\3.5\\scripts\\addons'
Installing biotite==0.36.1...
Using PyPI mirror: Default
Error: Error installing package. Please check the log files in 'C:\Users\DivjakMaja\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\MolecularNodes\logs'.

Installing MDAnalysis==2.2.0...
Using PyPI mirror: Default
Error: Error installing package. Please check the log files in 'C:\Users\DivjakMaja\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\MolecularNodes\logs'.
```

[side-packages-install.log](https://github.com/BradyAJohnston/MolecularNodes/files/11461071/side-packages-install.log)

**Screenshots**
![PrefsScreen](https://github.com/BradyAJohnston/MolecularNodes/assets/53807167/020bc4bc-0808-413a-a29b-909b891d86e6)

![MolNodesAddon](https://github.com/BradyAJohnston/MolecularNodes/assets/53807167/e0f99695-a6d8-440a-98c4-b53e2656ae42)

**Desktop (please complete the following information):**
 Windows 10 Pro
 - Intel(R) Xeon(R) CPU E5-2687W v4 @ 3.00GHz   3.00 GHz
 - Blender Version: 3.5.1
- MolecularNodes Version: 2.6.2

**Additional context**

**Comment by BradyAJohnston** [comment]
Hi Maja! Sorry that it's off to a rocky start. Looking at the `.log` file, it might be a problem with windows permissions. Can you start Blender by right-clicking and `Run as Administrator` to see if the packages can then be installed successfully?

**Comment by MajaDivjak** [comment]
I'll give it a whirl...Just writing you a message in Twitter....

**Comment by MajaDivjak** [comment]
Nope, no cigar...

**Comment by MajaDivjak** [comment]
I can try on my laptop once I get it home as the firewalls at the hospital are insane...Could be the issue

**Comment by BradyAJohnston** [comment]
I was just going to say, looking again at the logs, it seems like it might be a firewrall / connection issue: 
```
ERROR:root:stderr: WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001F0AF910280>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))': /simple/biotite/
```

Seems python is failing to get a good connection to download the required packages. Should hopefully work when not behind a strict firewall.

**Comment by MajaDivjak** [comment]
I tried tethering to my phone, but this still didn't work, probably because when you do that, certain folders become inaccessible and the addon might be trying to find them. Not sure where it writes to? Dunno. I'll test once home.

**Comment by BradyAJohnston** [comment]
We could potentially compile all of the required files and manually install it by copying and pasting if need be. So far at least most Windows machines haven't had too much trouble with installation that I am aware of.

**Comment by qqtonyokok** [comment]
my blender version is  3.4.1 windows
I have tried to run blender as an administrator.
what's wrong with this bug? 
**Screenshots**
![image](https://github.com/BradyAJohnston/MolecularNodes/assets/51323078/29af731f-3163-4f9d-b8ff-f8979615979f)
when i check import, bug come up 
![微信截图_20230515010528](https://github.com/BradyAJohnston/MolecularNodes/assets/51323078/1e630bb3-3b68-45de-bc60-45771c105b71)

**Comment by BradyAJohnston** [comment]
@qqtonyokok Molecular Nodes 2.6 requires Blender 3.5, so you have to update blender and this will fix your issue.

**Comment by qqtonyokok** [comment]
你好，我已收到你的邮件，如果有任何的问题，我会在查阅邮件后亲自联系你。

**Comment by qqtonyokok** [comment]
> 

thanks a lot now blender version 3.5 is OK，--!  God bless and thank you all so much

**Comment by MajaDivjak** [comment]
So, I managed to install Molecular Nodes on my laptop at home, bypassing the Peter Mac system, so it would seem to be the firewalls that are the problem. I have also been able to install on my desktop using my phone to tether. I forgot to turn off wifi last time, which is the reason it didn't work then. All was working well until I tried to import the 6n2y PDB structure and now everything has stopped working again with the following error message. I am working with Blender 3.5.1 and molecular nodes 2.7.0. If you could please advise, that would be great!

Read prefs: C:\Users\DivjakMaja\AppData\Roaming\Blender Foundation\Blender\3.5\config\userpref.blend
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\python\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\python\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\python\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\python\lib\site-packages\urllib3\connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\python\lib\site-packages\urllib3\connectionpool.py", line 994, in _prepare_proxy
    conn.connect()
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\python\lib\site-packages\urllib3\connection.py", line 358, in connect
    conn = self._new_conn()
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\python\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x00000207C96BF5B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\python\lib\site-packages\requests\adapters.py", line 440, in send
    resp = conn.urlopen(
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\python\lib\site-packages\urllib3\connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\python\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='mmtf.rcsb.org', port=443): Max retries exceeded with url: /v1.0/full/6n2y (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000207C96BF5B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\DivjakMaja\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\MolecularNodes\ui.py", line 41, in invoke
    return self.execute(context)
  File "C:\Users\DivjakMaja\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\MolecularNodes\ui.py", line 27, in execute
    mol_object = load.molecule_rcsb(
  File "C:\Users\DivjakMaja\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\MolecularNodes\load.py", line 81, in molecule_rcsb
    mol, file = open_structure_rcsb(
  File "C:\Users\DivjakMaja\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\MolecularNodes\load.py", line 174, in open_structure_rcsb
    file = mmtf.MMTFFile.read(rcsb.fetch(pdb_code, "mmtf"))
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\python\lib\site-packages\biotite\database\rcsb\download.py", line 119, in fetch
    r = requests.get(_mmtf_url + id)
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\python\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\python\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\python\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\python\lib\site-packages\requests\sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\python\lib\site-packages\requests\adapters.py", line 513, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='mmtf.rcsb.org', port=443): Max retries exceeded with url: /v1.0/full/6n2y (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000207C96BF5B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')))
Error: Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\python\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\python\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\python\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\python\lib\site-packages\urllib3\connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\python\lib\site-packages\urllib3\connectionpool.py", line 994, in _prepare_proxy
    conn.connect()
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\python\lib\site-packages\urllib3\connection.py", line 358, in connect
    conn = self._new_conn()
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\python\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x00000207C96BF5B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\python\lib\site-packages\requests\adapters.py", line 440, in send
    resp = conn.urlopen(
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\python\lib\site-packages\urllib3\connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\python\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='mmtf.rcsb.org', port=443): Max retries exceeded with url: /v1.0/full/6n2y (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000207C96BF5B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\DivjakMaja\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\MolecularNodes\ui.py", line 41, in invoke
    return self.execute(context)
  File "C:\Users\DivjakMaja\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\MolecularNodes\ui.py", line 27, in execute
    mol_object = load.molecule_rcsb(
  File "C:\Users\DivjakMaja\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\MolecularNodes\load.py", line 81, in molecule_rcsb
    mol, file = open_structure_rcsb(
  File "C:\Users\DivjakMaja\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\MolecularNodes\load.py", line 174, in open_structure_rcsb
    file = mmtf.MMTFFile.read(rcsb.fetch(pdb_code, "mmtf"))
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\python\lib\site-packages\biotite\database\rcsb\download.py", line 119, in fetch
    r = requests.get(_mmtf_url + id)
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\python\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\python\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\python\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\python\lib\site-packages\requests\sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "C:\Program Files\Blender Foundation\Blender 3.5\3.5\python\lib\site-packages\requests\adapters.py", line 513, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='mmtf.rcsb.org', port=443): Max retries exceeded with url: /v1.0/full/6n2y (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000207C96BF5B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')))

**Comment by qqtonyokok** [comment]
你好，我已收到你的邮件，如果有任何的问题，我会在查阅邮件后亲自联系你。

**Comment by BradyAJohnston** [comment]
@MajaDivjak looking at the error messages I would say it is likely the PeterMac firewall again. It seems that the downloading from the PDB is failing. Try maybe downloading from the PDB with your phone hotspot again? If that works, then you might need to ask IT to greenlight some of the IPs related to the PDB.

**Comment by MajaDivjak** [comment]
Thanks Brady,
I'll try at home again, but I did have the phone tethered the entire time...Such a pain working in a hospital

**Comment by MajaDivjak** [comment]
Hi Brady,
Indeed, everything works fine when I'm at home, so the firewalls are doing something it seems, even when I have my phone tethered. Same effect with Chimera X and mMaya. I've set everything up on the Pawsey so I can import structures unhindered and then copy back to Peter Mac. Royal pain. Will let IT know, but they are notoriously difficult to deal with when it comes to whitelisting.

**Comment by BradyAJohnston** [comment]
Hi @MajaDivjak, glad to hear that it seems to just be a firewall issue, although also frustrating. Please get in contact for other questions as well, excited that you are potentially going to be using it :)
