### ISSUE TITLE
ModuleNotFoundError: No module named 'pyopenvdb'

### ISSUE THREAD

**Issue by JoelTre** [BradyAJohnston/MolecularNodes#240]
**Describe the bug**
Hey! I have added Moleculnodes onto my desktop with no problems but now I am trying to add it to Blender on my acer laptop and it comes up with the error message: ModuleNotFoundError: No module named 'pyopenvdb'

I have no idea what this error means and how to solve it. 

**To Reproduce**
It comes up with this message after I have clicked install in the Blender AddOn page, added Molecular nodes and then click on the tick box to add it. I have tried redownloading the AddOn and moving it to a different folder but always comes up with the error. 

**Error Codes**
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Users\rebek\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\MolecularNodes\__init__.py", line 30, in <module>
    from .ui import *
  File "C:\Users\rebek\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\MolecularNodes\ui.py", line 7, in <module>
    from . import density
  File "C:\Users\rebek\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\MolecularNodes\density.py", line 2, in <module>
    import pyopenvdb as vdb
ModuleNotFoundError: No module named 'pyopenvdb'

**Desktop (please complete the following information):**
 - OS: Windows 
 - Hardware: Acer
 - Blender Version: 3.3.1
- MolecularNodes Version: 2.5.4

Thanks in advance for your help.

**Comment by BradyAJohnston** [comment]
You'll need to update Blender 3.5+. `pyopenvdb` is required for the later versions of Molecular Nodes and is only shipped with Blender 3.5+.

This should fix the problem!

P.S. there are also later versions of [MN available](https://github.com/BradyAJohnston/MolecularNodes/releases). I have realised the link in the documentation links to an older version so I am updating this.
