### ISSUE TITLE
KeyError: 'bpy_prop_collection[key]: key "Group Input" not found'

### ISSUE THREAD

**Issue by porunga00** [BradyAJohnston/MolecularNodes#29]
Hi, I'm trying "Download from the PDB" and "Load MD Trajectory File" according to your [document](https://bradyajohnston.github.io/MolecularNodes/getting-started.html).
However, I got the same error in both cases. Thanks!

```
Python: Traceback (most recent call last):
  File "C:\Users\ryohei.yamaguchi\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\molecular_nodes\__init__.py", line 2471, in invoke
    return self.execute(context)
  File "C:\Users\ryohei.yamaguchi\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\molecular_nodes\__init__.py", line 2458, in execute
    sna_func_import_structure_EE5B6(
  File "C:\Users\ryohei.yamaguchi\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\molecular_nodes\__init__.py", line 1583, in sna_func_import_structure_EE5B6
    sna_setup_node_tree_272D6(output_name, unique_chains, base_model,
  File "C:\Users\ryohei.yamaguchi\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\molecular_nodes\__init__.py", line 2599, in sna_setup_node_tree_272D6
    create_starting_node_tree(collection_of_properties=col_properties,
  File "C:\Users\ryohei.yamaguchi\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\molecular_nodes\__init__.py", line 2523, in create_starting_node_tree
    node_input = node_mod.node_group.nodes['Group Input']
KeyError: 'bpy_prop_collection[key]: key "Group Input" not found'

location: <unknown location>:-1
```

**Comment by BradyAJohnston** [comment]
Thanks for reporting the bug! Are you able to give more info as to what version of Molcular Nodes you are using, which Blender version and what OS you are working on?

**Comment by porunga00** [comment]
Molecular Nodes: 0.5.20
Blender: 3.1.2
OS: Windows11
mdanalysis: 2.1.0 (Build: py310hf5e1058_4, Repository: conda-forge)

**Comment by BradyAJohnston** [comment]
I can't seem to replicate the issue at all. Are you able to provide screenshots of what Blender looks like after attempting import? It seems like the protein might be imported correctly but that the node trees fail when being set up. 

This is a known issue for Blender 3.2 beta which I am yet to fix, but I haven't come across it in earlier versions.

**Comment by porunga00** [comment]
I switched the Blender's language from Japanese to English to take screenshots and the error was resolved! Thanks!

**Comment by BradyAJohnston** [comment]
An interesting bug - I wouldn't have thought that language would cause this kind of error, but glad to know it's resolved!

**Comment by BradyAJohnston** [comment]
Reopening this issue to coincide with #41, I will be attempting to fix the broken python API in non-english language settings.

**Comment by BradyAJohnston** [comment]
Now tracking in #63
