### ISSUE TITLE
Loading pdb with a membrane : List Index Out of range

### ISSUE THREAD

**Issue by tubiana** [BradyAJohnston/MolecularNodes#48]
Hi Brady :) 

I wanted to reproduce a previous picture with the geometry made with ChimeraX, but with your nodes :) 

The PDB Contains a transmembrane protein with a membrane and I have this error message : 

```python
Python: Traceback (most recent call last):
  File "C:\Users\tubia\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\molecular_nodes\__init__.py", line 1147, in sna_func_import_structure_EE5B6
    try_append(atom_element_char, get_element(atom))
  File "C:\Users\tubia\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\molecular_nodes\__init__.py", line 1116, in get_element
    element = element_from_atom_name(atom.name)
  File "C:\Users\tubia\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\molecular_nodes\__init__.py", line 1108, in element_from_atom_name
    return re.findall("^[A-Z][a-z]?", atom_name)[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\tubia\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\molecular_nodes\__init__.py", line 744, in invoke
    return self.execute(context)
  File "C:\Users\tubia\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\molecular_nodes\__init__.py", line 740, in execute
    sna_func_import_structure_EE5B6(bpy.context.scene.sna_pdb_code, bpy.context.scene.sna_nanometre_scale, False, bpy.context.scene.sna_pdb_path, bpy.context.scene.sna_molecule_name, bpy.context.scene.sna_create_bonds, bpy.context.scene.sna_connect_cutoff, bpy.context.scene.sna_build_assembly, bpy.context.scene.sna_build_assembly_id)
  File "C:\Users\tubia\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\molecular_nodes\__init__.py", line 1163, in sna_func_import_structure_EE5B6
    try_append(atom_element_char, get_element(atom))
  File "C:\Users\tubia\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\molecular_nodes\__init__.py", line 1116, in get_element
    element = element_from_atom_name(atom.name)
  File "C:\Users\tubia\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\molecular_nodes\__init__.py", line 1108, in element_from_atom_name
    return re.findall("^[A-Z][a-z]?", atom_name)[0]
IndexError: list index out of range

```
I'm not sure if the problem is comming from the PDB / Atomium or something with the node... But I leave the PDB here :)

Thanks :) 
Thibault.

**Comment by BradyAJohnston** [comment]
Thanks for flagging the issue, should now be fixed in v0.10 https://github.com/BradyAJohnston/MolecularNodes/releases/tag/v0.10

**Comment by tubiana** [comment]
Wow thanks for the quick fix =D
