### ISSUE TITLE
Can't import PDB structures from within blender

### ISSUE THREAD

**Issue by PATTHU1** [BradyAJohnston/MolecularNodes#539]
**Describe the bug**
I can't import PDB structures by inputting the 4 letter code. It gives me this error message

**Error Codes**
```
Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\site-packages\urllib3\util\connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\site-packages\urllib3\connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\site-packages\urllib3\connection.py", line 358, in connect
    conn = self._new_conn()
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000001C556929D80>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\site-packages\requests\adapters.py", line 440, in send
    resp = conn.urlopen(
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\site-packages\urllib3\connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='mmtf.rcsb.org', port=443): Max retries exceeded with url: /v1.0/full/1AB2 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001C556929D80>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\site-packages\requests\sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\python\lib\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='mmtf.rcsb.org', port=443): Max retries exceeded with url: /v1.0/full/1AB2 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001C556929D80>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
![image](https://github.com/BradyAJohnston/MolecularNodes/assets/174809068/c2388435-732c-4631-bc5e-bad4ebfa1fa0)

``` 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows / MacOS / Linux]
 - Hardware: [e.g. Intel Mac, M1 Mac, x86 PC]
 - Blender Version: 
- MolecularNodes Version:

**Additional context**

**Comment by BradyAJohnston** [comment]
The PDB has stopped serving downloads of `.mmtf` which MN used to use for downloading: https://www.rcsb.org/news/663129f765d8a8cacaf76f9f

Either switch to a different format for downloading or I recommend upgrading to Blender / MN 4.1.
