### ISSUE TITLE
AttributeError: 'ShaderNodeBsdfPrincipled' object has no attribute 'node_tree'

### ISSUE THREAD

**Issue by xmx-emm** [BradyAJohnston/MolecularNodes#561]
**Describe the bug**

**To Reproduce**
in node interface

```
Traceback (most recent call last):
  File "D:\SteamLibrary\steamapps\common\Blender\4.3\scripts\modules\bpy_types.py", line 1034, in draw_ls
    func(self, context)
  File "C:\Users\EM1\AppData\Roaming\Blender Foundation\Blender\4.3\extensions\blender_org\molecularnodes\ui\panel.py", line 92, in change_style_node_menu
    prefix = node.node_tree.name.split(" ")[0].lower()
             ^^^^^^^^^^^^^^
AttributeError: 'ShaderNodeBsdfPrincipled' object has no attribute 'node_tree'
```

**Desktop (please complete the following information):**
 - OS: [e.g. Windows / MacOS / Linux]
 - Hardware: [e.g. Intel Mac, M1 Mac, x86 PC]
 - Blender Version: 4.3.0 Alpha
- MolecularNodes Version:4.2.4

**Additional context**

**Comment by BradyAJohnston** [comment]
You haven't provided any extra information - I don't know what bug you are reporting. If you can provide more information we can reopen the issue
