### ISSUE TITLE
VSCode development addon isue with extension?

### ISSUE THREAD

**Issue by jojoelfe** [BradyAJohnston/MolecularNodes#600]
I am having issues using the VSCode development addon with blender 4.2.1. The extension fails to activate because either 'starfile' or 'biotite' are not available. These should be installed through the new extensions platform, right? The log output is:

```
Executing task: /groups/cryoadmin/software/BLENDER/blender-4.2.1-linux-x64/blender --python /groups/elferich/.vscode/extensions/jacqueslucke.blender-development-0.0.21/pythonFiles/launch.py 

[{'load_dir': '/groups/elferich/Documents/MolecularNodes/molecularnodes', 'module_name': 'molecularnodes'}]
USER ADDON: /groups/elferich/.config/blender/4.2/extensions/user_default
 * Serving Flask app 'Blender Server'
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:6835
Press CTRL+C to quit
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
Sending: {'type': 'setup', 'blenderPort': 6835, 'debugpyPort': 3615, 'blenderPath': '/groups/cryoadmin/software/BLENDER/blender-4.2.1-linux-x64/blender', 'scriptsFolder': '/groups/cryoadmin/software/BLENDER/blender-4.2.1-linux-x64/4.2/scripts', 'addonPathMappings': [{'src': '/groups/elferich/Documents/MolecularNodes/molecularnodes', 'load': '/groups/elferich/.config/blender/4.2/extensions/user_default/molecularnodes'}]}
Waiting for debug client.
Debug client attached.
Warning: extensions.blender.org: [Errno 2] No such file or directory: '/groups/elferich/.config/blender/4.2/extensions/blender_org'
Skipping wheel for other system (macosx_10_9_x86_64 != linux_x86_64): MDAnalysis-2.7.0-cp311-cp311-macosx_10_9_x86_64.whl
Skipping wheel for other system (macosx_11_0_arm64 != linux_x86_64): MDAnalysis-2.7.0-cp311-cp311-macosx_11_0_arm64.whl
Skipping wheel for other system (win_amd64 != linux_x86_64): MDAnalysis-2.7.0-cp311-cp311-win_amd64.whl
Skipping wheel for other system (macosx_10_9_x86_64 != linux_x86_64): biotite-0.41.2-cp311-cp311-macosx_10_9_x86_64.whl
Skipping wheel for other system (macosx_11_0_arm64 != linux_x86_64): biotite-0.41.2-cp311-cp311-macosx_11_0_arm64.whl
Skipping wheel for other system (win_amd64 != linux_x86_64): biotite-0.41.2-cp311-cp311-win_amd64.whl
Skipping wheel for other system (macosx_10_9_x86_64 != linux_x86_64): contourpy-1.2.1-cp311-cp311-macosx_10_9_x86_64.whl
Skipping wheel for other system (macosx_11_0_arm64 != linux_x86_64): contourpy-1.2.1-cp311-cp311-macosx_11_0_arm64.whl
Skipping wheel for other system (win_amd64 != linux_x86_64): contourpy-1.2.1-cp311-cp311-win_amd64.whl
Skipping wheel for other system (macosx_10_9_universal2 != linux_x86_64): fonttools-4.53.1-cp311-cp311-macosx_10_9_universal2.whl
Skipping wheel for other system (macosx_11_0_arm64 != linux_x86_64): fonttools-4.53.1-cp311-cp311-macosx_11_0_arm64.whl
Skipping wheel for other system (win_amd64 != linux_x86_64): fonttools-4.53.1-cp311-cp311-win_amd64.whl
Skipping wheel for other system (macosx_10_9_x86_64 != linux_x86_64): kiwisolver-1.4.5-cp311-cp311-macosx_10_9_x86_64.whl
Skipping wheel for other system (macosx_11_0_arm64 != linux_x86_64): kiwisolver-1.4.5-cp311-cp311-macosx_11_0_arm64.whl
Skipping wheel for other system (win_amd64 != linux_x86_64): kiwisolver-1.4.5-cp311-cp311-win_amd64.whl
Skipping wheel for other system (macosx_10_12_x86_64 != linux_x86_64): matplotlib-3.9.1.post1-cp311-cp311-macosx_10_12_x86_64.whl
Skipping wheel for other system (macosx_11_0_arm64 != linux_x86_64): matplotlib-3.9.1.post1-cp311-cp311-macosx_11_0_arm64.whl
Skipping wheel for other system (win_amd64 != linux_x86_64): matplotlib-3.9.1.post1-cp311-cp311-win_amd64.whl
Skipping wheel for other system (macosx_10_9_x86_64 != linux_x86_64): msgpack-1.0.8-cp311-cp311-macosx_10_9_x86_64.whl
Skipping wheel for other system (macosx_11_0_arm64 != linux_x86_64): msgpack-1.0.8-cp311-cp311-macosx_11_0_arm64.whl
Skipping wheel for other system (win_amd64 != linux_x86_64): msgpack-1.0.8-cp311-cp311-win_amd64.whl
Skipping wheel for other system (macosx_10_9_x86_64 != linux_x86_64): pandas-2.2.2-cp311-cp311-macosx_10_9_x86_64.whl
Skipping wheel for other system (macosx_11_0_arm64 != linux_x86_64): pandas-2.2.2-cp311-cp311-macosx_11_0_arm64.whl
Skipping wheel for other system (win_amd64 != linux_x86_64): pandas-2.2.2-cp311-cp311-win_amd64.whl
Skipping wheel for other system (macosx_10_10_x86_64 != linux_x86_64): pillow-10.4.0-cp311-cp311-macosx_10_10_x86_64.whl
Skipping wheel for other system (macosx_11_0_arm64 != linux_x86_64): pillow-10.4.0-cp311-cp311-macosx_11_0_arm64.whl
Skipping wheel for other system (win_amd64 != linux_x86_64): pillow-10.4.0-cp311-cp311-win_amd64.whl
Skipping wheel for other system (macosx_10_9_x86_64 != linux_x86_64): scipy-1.14.0-cp311-cp311-macosx_10_9_x86_64.whl
Skipping wheel for other system (macosx_12_0_arm64 != linux_x86_64): scipy-1.14.0-cp311-cp311-macosx_12_0_arm64.whl
Skipping wheel for other system (win_amd64 != linux_x86_64): scipy-1.14.0-cp311-cp311-win_amd64.whl
Traceback (most recent call last):
  File "/groups/cryoadmin/software/BLENDER/blender-4.2.1-linux-x64/4.2/scripts/modules/addon_utils.py", line 407, in enable
    mod = importlib.import_module(module_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/groups/cryoadmin/software/BLENDER/blender-4.2.1-linux-x64/4.2/python/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/groups/elferich/.config/blender/4.2/extensions/user_default/molecularnodes/__init__.py", line 17, in <module>
    from . import entities, operators, props, session, ui
  File "/groups/elferich/.config/blender/4.2/extensions/user_default/molecularnodes/entities/__init__.py", line 1, in <module>
    from . import molecule, trajectory
  File "/groups/elferich/.config/blender/4.2/extensions/user_default/molecularnodes/entities/molecule/__init__.py", line 1, in <module>
    from .pdbx import BCIF, CIF
  File "/groups/elferich/.config/blender/4.2/extensions/user_default/molecularnodes/entities/molecule/pdbx.py", line 4, in <module>
    import biotite.structure as struc
ModuleNotFoundError: No module named 'biotite'
Error: No module named 'biotite'
Traceback (most recent call last):
  File "/groups/elferich/.vscode/extensions/jacqueslucke.blender-development-0.0.21/pythonFiles/include/blender_vscode/load_addons.py", line 57, in load
    bpy.ops.preferences.addon_enable(module=addon_name)
  File "/groups/cryoadmin/software/BLENDER/blender-4.2.1-linux-x64/4.2/scripts/modules/bpy/ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: No module named 'biotite'

Sending: {'type': 'enableFailure', 'addonPath': '/groups/elferich/Documents/MolecularNodes/molecularnodes'}
```

This might actually bean issue with the addon or my system, but I wonder if you are doing something else for development that I am missing...

**Comment by jojoelfe** [comment]
AH, running these two commands fixed it:
```
blender -b -P tests/python.py -- -m pip install tomlkit
blender -b -P build.py
```

Is this something the VSCode addon could do or should the instructions on Readme.md  get updated?

**Comment by BradyAJohnston** [comment]
Apologies about this! I actually temporarily stopped using the VSCode plugin for development while 4.2 was coming around as it wasn't updated to work with it (was just creating symlinks myself), and I hadn't revisited it or the docs for it. 

I'll need to update the documentation with your suggestions :)

**Comment by BradyAJohnston** [comment]
I've add it to the docs, but installing tomlkit is now part of the `build.py` so you just need to run the second line
