### ISSUE TITLE
Molecular Nodes 

### ISSUE THREAD

**Issue by NNBBD** [BradyAJohnston/MolecularNodes#62]
![image](https://user-images.githubusercontent.com/64623225/185053288-e65ff950-3619-4f8a-8424-7361dc2e09e2.png)
I can't use it properly
blender tell me
Python: Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\molecular_nodes\__init__.py", line 1484, in invoke
    return self.execute(context)
  File "C:\Users\ASUS\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\molecular_nodes\__init__.py", line 1480, in execute
    sna_func_import_structure_EE5B6(bpy.context.scene.sna_pdb_code, bpy.context.scene.sna_nanometre_scale, True, bpy.context.scene.sna_pdb_path, bpy.context.scene.sna_molecule_name, bpy.context.scene.sna_create_bonds, bpy.context.scene.sna_connect_cutoff, bpy.context.scene.sna_build_assembly, bpy.context.scene.sna_build_assembly_id)
  File "C:\Users\ASUS\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\molecular_nodes\__init__.py", line 2259, in sna_func_import_structure_EE5B6
    sna_setup_node_tree_272D6(output_name, unique_chains, base_model, col_properties, col_frames, assemblies, n_frames)
  File "C:\Users\ASUS\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\molecular_nodes\__init__.py", line 2752, in sna_setup_node_tree_272D6
    create_starting_node_tree(collection_of_properties=col_properties, obj = base_model)
  File "C:\Users\ASUS\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\molecular_nodes\__init__.py", line 2693, in create_starting_node_tree
    node_input = node_mod.node_group.nodes['Group Input']
KeyError: 'bpy_prop_collection[key]: key "Group Input" not found'

**Comment by BradyAJohnston** [comment]
Do you have Blender set to a different language at all? If so, can you try setting to English and see if it fixes the issue as in #55

**Comment by NNBBD** [comment]
thanks for your reminding~
