### ISSUE TITLE
Non-English Blender Breaks Node Setup on Import

### ISSUE THREAD

**Issue by BradyAJohnston** [BradyAJohnston/MolecularNodes#63]
When Blender is set to non-English languages, the initial node setup fails.

Documented cases: #62, #55, #41, #29. 

Closing all of those issues and documenting here.

**Comment by YaoYinYing** [comment]
Hi Brady, 

FYI, I changed my language setting and inserted a debug line `raise ValueError(node_mod.node_group.nodes.keys())` in `/Users/yyy/Library/Application Support/Blender/3.4/scripts/addons/MolecularNodes/nodes.py:115` and restart Blender for reloading this addon, then load a PDB and it reported the following:

```python
Python: Traceback (most recent call last):
  File "/Users/yyy/Library/Application Support/Blender/3.4/scripts/addons/MolecularNodes/ui.py", line 41, in invoke
    return self.execute(context)
  File "/Users/yyy/Library/Application Support/Blender/3.4/scripts/addons/MolecularNodes/ui.py", line 27, in execute
    mol_object = load.molecule_rcsb(
  File "/Users/yyy/Library/Application Support/Blender/3.4/scripts/addons/MolecularNodes/load.py", line 27, in molecule_rcsb
    nodes.create_starting_node_tree(
  File "/Users/yyy/Library/Application Support/Blender/3.4/scripts/addons/MolecularNodes/nodes.py", line 115, in create_starting_node_tree
    raise ValueError(node_mod.node_group.nodes.keys())
ValueError: ['组输入', '组输出']
```
it looks like blender has already translated the keys into simplified Chinese.

**Comment by YaoYinYing** [comment]
I was thinking that if someone prefers to use their native language in Blender, we could launch a translation project to replace all keys in the MolecularNodes addon that have already been defined by Blender in different languages, and create a toggle option or automatically detect the language setting to select the correct translation.

**Comment by BradyAJohnston** [comment]
Thanks for looking into this. 

Looking at the error, Blender is translating the names for the default nodes, but I am trying to request them via their English translation keys. 

https://github.com/BradyAJohnston/MolecularNodes/blob/9e77b1e304d9bb4210254c50a1167faa24625bcc/MolecularNodes/nodes.py#L115-L118

This should only be a problem for the default nodes potentially. Having to create our own translation of each of the nodes would potentially be a lot of work. What might be a better approach is to find a different way to reference these particular nodes, like the underlying RNA values of the nodes that shouldn't change regardless of the language.

Do the node inputs get translated in a different language? All of the sliders / geometry etc because I am calling them by name also, but could switch to using integer values for them instead which would be language-agnostic.

**Comment by YaoYinYing** [comment]
I found something in the offical [translation documents](https://docs.blender.org/api/current/bpy.app.translations.html#bpy.app.translations.pgettext_data) which suggests that  Blender has a build-in API for translation.

As seen in this code 
https://github.com/BradyAJohnston/MolecularNodes/blob/bc6e1b932737725cbd13e41577d64b6cbfefe108/MolecularNodes/nodes.py#L114-L118

the API can be used in the following way:
```python
    # move the input and output nodes for the group
    node_input = node_mod.node_group.nodes[bpy.app.translations.pgettext("Group Input",)]
    node_input.location = [0, 0]
    node_output = node_mod.node_group.nodes[bpy.app.translations.pgettext("Group Output",)]
    node_output.location = [800, 0]
```
This translation can be seemlessly done when one sets his/her native language in Blender.

**Comment by YaoYinYing** [comment]
In this circonstance, the translations of all texts in this addon can be easily done!
