### ISSUE TITLE
Blender 3.3, DNA Base Colour Node couldn't be loaded

### ISSUE THREAD

**Issue by jgaertner** [BradyAJohnston/MolecularNodes#72]
Following your DNA tutorial:
Couldn't load "DNA Base Colour", "DNA Base Custome", "DNA Style Surface" and "DNA Style Ball n Stick" nodes.

Python: Traceback (most recent call last):
  File "C:\Users\juang\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\molecular_nodes\__init__.py", line 418, in invoke
    return self.execute(context)
  File "C:\Users\juang\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\molecular_nodes\__init__.py", line 413, in execute
    sna_just_append_node_group_D75AA(self.sna_node_name)
  File "C:\Users\juang\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\molecular_nodes\__init__.py", line 2039, in sna_just_append_node_group_D75AA
    bpy.ops.wm.append(directory=os.path.join(os.path.dirname(__file__), 'assets', 'molecular_nodes_append_file.blend') + r'\NodeTree', filename=node_group, link=False)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Operator bpy.ops.wm.append.poll() failed, context is incorrect

**Comment by jgaertner** [comment]
I can load this nodes with a "fresh" blender file, but after loading some other nodes, I can't load the 4 nodes above mentioned. I have then also another issue with blender: under menu "file" "link" and "append" are grayed out.

**Comment by jgaertner** [comment]
Solved the problem. This only happens when the bezier curve is in edit mode.
