### ISSUE TITLE
Atomium and big pdb file?

### ISSUE THREAD

**Issue by tubiana** [BradyAJohnston/MolecularNodes#9]
Hello Brady :) 

Long time ago I made a video on VMD of my Norovirus Capsid, and I thought that it could be a good test for your tool (Since I have 600K+ atom in the PDB).
Here it is (just 1 state) [morph_state001-capsid.zip](https://github.com/BradyAJohnston/MolecularNodes/files/8586192/morph_state001-capsid.zip)

The problem is that only one part seems to be read since the numbering stop at 99999 (cf. Screenshot 1). I tried different format (convertion with Pymol to mmtf, mmcif, cif, pdb.gz, cif.gz) and it fails for other format (But here the problem seems to come from the atomium library for reading mmtf or mmcif when the output comme from Pymol maybe ?)

For this issue maybe the problem come from the atomium library itself ? But I wanted to repport it since with this new render system it seems possible to load very big systems, and unfortunatly the "assembly" coming from the PDB is splitted into different models (so your addon think it's a trajectory)

Anyway, here's some extra information ⤵️ and thank you again for this already great piece of work =D
Thibault.

Screenshot 1: 
![image](https://user-images.githubusercontent.com/8037224/165841752-17fbf973-d3e3-475c-b2f0-fccfcba4517c.png)

traceback for loading when it's mmtf
```python 
Python: Traceback (most recent call last):
  File "C:\Users\tubia\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\molecular_nodes\__init__.py", line 80, in execute
    sna_func_import_structure_EE5B6(bpy.context.scene.sna_pdb_code,
  File "C:\Users\tubia\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\molecular_nodes\__init__.py", line 1137, in sna_func_import_structure_EE5B6
    pdb = atomium.open(pdb_path)
  File "C:\Users\tubia\AppData\Roaming\Python\Python310\site-packages\atomium\utilities.py", line 41, in open
    return parse_string(filestring, path, *args, **kwargs)
  File "C:\Users\tubia\AppData\Roaming\Python\Python310\site-packages\atomium\utilities.py", line 122, in parse_string
    parsed = file_func(filestring)
  File "C:\Users\tubia\AppData\Roaming\Python\Python310\site-packages\atomium\mmtf.py", line 18, in mmtf_bytes_to_mmtf_dict
    return decode_dict(raw)
  File "C:\Users\tubia\AppData\Roaming\Python\Python310\site-packages\atomium\mmtf.py", line 40, in decode_dict
    new_value = [decode_dict(x) for x in new_value]
  File "C:\Users\tubia\AppData\Roaming\Python\Python310\site-packages\atomium\mmtf.py", line 40, in <listcomp>
    new_value = [decode_dict(x) for x in new_value]
  File "C:\Users\tubia\AppData\Roaming\Python\Python310\site-packages\atomium\mmtf.py", line 37, in decode_dict
    new_value = parse_binary_field(new_value)
  File "C:\Users\tubia\AppData\Roaming\Python\Python310\site-packages\atomium\mmtf.py", line 56, in parse_binary_field
    codec, length, params = struct.unpack(">iii", b[:12])
struct.error: unpack requires a buffer of 12 bytes

location: <unknown location>:-1
```

Traceback for loading when it's mmcif
```python
Python: Traceback (most recent call last):
  File "C:\Users\tubia\AppData\Roaming\Python\Python310\site-packages\atomium\pdb.py", line 506, in add_atom_to_non_polymer
    ] = atom_line_to_dict(line, aniso_dict)
  File "C:\Users\tubia\AppData\Roaming\Python\Python310\site-packages\atomium\pdb.py", line 530, in atom_line_to_dict
    a["x"] = float(line[30:38].strip())
ValueError: could not convert string to float: '9 ? -57.'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\tubia\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\molecular_nodes\__init__.py", line 80, in execute
    sna_func_import_structure_EE5B6(bpy.context.scene.sna_pdb_code,
  File "C:\Users\tubia\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\molecular_nodes\__init__.py", line 1137, in sna_func_import_structure_EE5B6
    pdb = atomium.open(pdb_path)
  File "C:\Users\tubia\AppData\Roaming\Python\Python310\site-packages\atomium\utilities.py", line 41, in open
    return parse_string(filestring, path, *args, **kwargs)
  File "C:\Users\tubia\AppData\Roaming\Python\Python310\site-packages\atomium\utilities.py", line 124, in parse_string
    parsed = data_func(parsed)
  File "C:\Users\tubia\AppData\Roaming\Python\Python310\site-packages\atomium\pdb.py", line 86, in pdb_dict_to_data_dict
    update_models_list(pdb_dict, data_dict)
  File "C:\Users\tubia\AppData\Roaming\Python\Python310\site-packages\atomium\pdb.py", line 158, in update_models_list
    add_atom_to_non_polymer(line, model, res_id, aniso, full_names)
  File "C:\Users\tubia\AppData\Roaming\Python\Python310\site-packages\atomium\pdb.py", line 512, in add_atom_to_non_polymer
    "atoms": {int(line[6:11]): atom_line_to_dict(line, aniso_dict)}
  File "C:\Users\tubia\AppData\Roaming\Python\Python310\site-packages\atomium\pdb.py", line 530, in atom_line_to_dict
    a["x"] = float(line[30:38].strip())
ValueError: could not convert string to float: '9 ? -57.'

location: <unknown location>:-1
```

**Comment by BradyAJohnston** [comment]
Ah yes currently I have it treat a multi-model PDB as different frames. I'll add an option to import them all as one big structure and not different frames.

Should potentially fix it, and then we can try and address the mmcif problems.

**Comment by BradyAJohnston** [comment]
Have had a look at the file as well, and I get the same error if I save it as a `.mmcif` and try to open with `atomium`, but can open it fine if it is a `.pdb` file. Seems like an `atomium` error I'll report it to the devs :)

**Comment by BradyAJohnston** [comment]
I was able to at least download and render without an issue [`7N6Y`](https://www.rcsb.org/structure/7N6Y) from the PDB and build the biological assembly: 
![noravirus](https://user-images.githubusercontent.com/36021261/165882340-89f407a7-38fa-4e71-934e-a78fe2b23987.png)

**Comment by tubiana** [comment]
Wow that's so nice =D 

Did you do something with the PDB before loading it with your plugin? I only have the assymetric unit loaded... Maybe there is a way to show all frames and I missed it ?
*sorry about the quality, it is a quick test from my macbook...*
![image](https://user-images.githubusercontent.com/8037224/165951029-27f65684-2dc7-4eba-b807-c4777d92a85b.png)

By the way! I don't know if there is a way to color by chain directly from your addon, so I dig a bit arround and made a node from your "color per atom" node! 
If have to say, once we grasp how it works, it's pretty easy =D 
Here's my node, in case someone else need it :-)
![image](https://user-images.githubusercontent.com/8037224/165951210-d0757629-6345-4d30-90a4-f7da1822559d.png)
![image](https://user-images.githubusercontent.com/8037224/165951241-9f85f4c9-e63e-447d-8e8f-1520d8e3a498.png)

**Comment by BradyAJohnston** [comment]
Nice work on the node! I am trying to think of the best way to do colouring per chain. Each protein will have a different number of chains, and the lettering etc will be different, so I am unsure how to approach it yet. Each protein will need its own custom colour by chain node (like you have made), so I am experimenting with creating a new node on import, to save having to have the user make it. We shall see how successful I am!

But nice work on the nodes, glad it's mostly making sense!

**Comment by BradyAJohnston** [comment]
Hey @tubiana is this still something that you are having trouble with? I assume the `mmcif` parsing is still problematic, but are you able to build biological assembly OK now?

**Comment by RodenLuo** [comment]
Hi, 

Just so you know that I just loaded [6Z7N ](https://www.rcsb.org/structure/6Z7N) in its mmcif format and build the biological assembly. It took about 3 minutes on my machine. Below is a screenshot that looks correct. (I still have to learn the shading in blender to get it a nicer look though.)

![image](https://user-images.githubusercontent.com/8460424/167131175-223218ed-838f-4059-8da0-56962f181c1a.png)

**Comment by BradyAJohnston** [comment]
Thanks @RodenLuo for the feedback! Good to know that it builds OK from `.mmcif` format. Seems like the problem might be resolved.
